apiVersion: v1
kind: Secret
metadata:
  name: {{ include "notion-kroki-bridge.fullname" . }}
  labels:
    {{- include "notion-kroki-bridge.labels" . | nindent 4 }}
type: Opaque
data:
  notionApiToken: "{{ .Values.notionApiToken }}"
